export const productContants = {
  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAILED: "GET_PRODUCT_FAILED",
  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILED: "ADD_PRODUCT_FAILED",
};

export const authContants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT_SUCCES: "LOGOUT_SUCCES",
};

export const tabContants = {
  GET_TAB_SUCCESS: "GET_TAB_SUCCESS",
  DELETE_TAB_SUCCESS: "DELETE_TAB_SUCCESS",
};
